# Generated by Django 2.1.1 on 2019-02-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_programm_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Горячие блюда', 'Горячие блюда'), ('Завтраки', 'Завтраки'), ('Смузи', 'Смузи'), ('Продукт', 'Продукт')], default='Продукт', max_length=100),
        ),
    ]
